#!/bin/bash

# ASCII Art
ascii_art="

 ███╗   ███╗ █████╗ ███████╗
 ████╗ ████║██╔══██╗╚══███╔╝
 ██╔████╔██║███████║  ███╔╝ 
 ██║╚██╔╝██║██╔══██║ ███╔╝  
 ██║ ╚═╝ ██║██║  ██║███████╗
 ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝
                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Clear the screen
clear
# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"


echo "* Installing Dependencies"

# Update package list and install dependencies
git clone https://github.com/achul123/skyportd.git
cd skyportd 
npm install

echo_message "* cd skyportd"

echo_message "* paste your configure code"

echo_message "* pm2 start ."
